Added HTTP lesson in TypeScript
marcduiker/azure-functions-university pull request #27
Opened 2021-03-12 15:54 UTC by lechnerc77

Referring to issue #17 I have added a TypeScript version for the HTTP Trigger lesson based on the .NET HTTP Trigger lesson. 
I also added Code Tours for the different sections of the lesson and the homework in the corresponding source code folders.

2021-03-30 07:24 UTC, marcduiker commented
Thanks @lechnerc77,  I'll start the review this week!

2021-03-31 06:43 UTC, lechnerc77 commented on lessons/prerequisites-ts.md
> +# Prerequisites
Done - updated the descriptions. Not sure if I am happy with the layout, so please check

2021-03-31 06:46 UTC, lechnerc77 commented on lessons/prerequisites-ts.md
> +|[Node.js](https://nodejs.org/en/download/)|All| The Node.js runtime including the node package manager NPM.
I added a remark with respect to LTS version. As LTS versions change every year I wouldn't pick a specific version.

2021-03-31 06:46 UTC, lechnerc77 commented on lessons/http-ts.md
> +# HTTP Trigger
Done - I also updated the header in the .NET file

2021-03-31 06:46 UTC, lechnerc77 commented on lessons/http-ts.md
> +1. Copy & paste the folder of the Azure Function from the exercise above and give it a new name e.g. CustomGreetingHttpTrigger.
Done

2021-03-31 06:47 UTC, lechnerc77 commented on lessons/http-ts.md
> +
Done

2021-03-31 06:47 UTC, lechnerc77 commented on lessons/http-ts.md
> +- A brief overview [video](https://youtu.be/Wbw6MS5VoDo) by Gwyneth Pena
Removed it

2021-03-31 08:15 UTC, marcduiker requested changes
This PR also contains the work from Stacy and myself on the Configuration lesson. Perhaps you need to rebase your branch on main on the original repo?

In addition the CodeTour files are not discovered in VSCode. I can open them manually but then the steps don't navigate to the right files (I do see the comments themselves).

2021-03-31 08:48 UTC, marcduiker commented
Even when I add a new CodeTour it does not work, very weird. I'll try it on the main branch in my repo for a .NET project.

2021-03-31 09:00 UTC, lechnerc77 commented
Concerning the CodeTour => the files currently reference the main branch (in the JSON file of the code tour). If you change that to "http_ts" the code tour should work

For the git "chaos" - I have to check (especially if my git skills are sufficient to solve it

2021-03-31 11:10 UTC, marcduiker commented
I pushed a small tour file in the `main` branch. I think the tour files all need to be in a `.tour` folder in the root. You can have subfolders inside that folder. https://github.com/microsoft/codetour#tour-files

2021-04-01 10:51 UTC, lechnerc77 commented
>Let me know, we can go on a call and fix this together if you'd like.

Help would be highly appreciated here - no idea what went sideways here.


> I pushed a small tour file in the `main` branch. I think the tour files all need to be in a `.tour` folder in the root. You can have subfolders inside that folder. https://github.com/microsoft/codetour#tour-files

I check the .tour file options and adjust accordingly

2021-04-02 15:27 UTC, lechnerc77 commented
Messed up git :-)

2021-04-02 15:27 UTC, closed without merging